name: build_docker

on:
  push:
    branches: [main]
  release:
    types: [created] # 表示在创建新的 Release 时触发

jobs:
  build_docker: #构建docker并发布到dockerhub上
    name: Build docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: |
          echo "本次构建的版本为：${GITHUB_REF_NAME} (但是这个变量目前上下文中无法获取到)"
          echo 本次构建的版本为：${{ github.ref_name }}
          env

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/chatgpt-web:${{ github.ref_name }}
            ${{ secrets.DOCKERHUB_USERNAME }}/chatgpt-web:latest

  bt-product-release: #构建docker并发布到阿里云容器镜像中
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # pull代码到运行服务器上
      - name: Login to Aliyun Container Registry (ACR)
        uses: aliyun/acr-login@v1 # 使用阿里云镜像服务action
        with:
          login-server: registry.cn-hangzhou.aliyuncs.com # 务必正确填写镜像容器服务的登录地址
          region-id: cn-hangzhou # 务必正确填写镜像容器服务的登录地址
          username: ${{ secrets.DOCKERHUB_ALIYUN_USERNAME }} # 引用GitHub repo设置的镜像容器服务用户名
          password: ${{ secrets.DOCKERHUB_ALIYUN_PASSWORD }} # 引用GitHub repo设置的镜像容器服务密码
      - name: Build and Push Docker Image
        env:
          IMAGE_TAG: ${{ github.sha }} # 用于标记容器版本号
        run: |
          docker build -t registry.cn-hangzhou.aliyuncs.com/chenyue/chatgpt-web:$IMAGE_TAG .
          docker push registry.cn-hangzhou.aliyuncs.com/chenyue/chatgpt-web:$IMAGE_TAG
